# A basic workflow that sends a daily briefing

name: daily_briefing

on:
  schedule:
  - cron: '45 06 * * *'
  # [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  daily_briefing:
  # The type of runner that the job will run on
    runs-on: ubuntu-18.04
  # retrieve secrets from github
    env:
      USERNAME: ${{ secrets.USERNAME}}
      PASSWORD: ${{ secrets.PASSWORD}}
      RECIPIENT: ${{ secrets.RECIPIENT}}
      RENV_PATHS_ROOT: ~/.local/share/renv
    #
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0.2'
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      # install renv package
      - name: Install renv package
        run: R -e 'install.packages("renv")'
      # set up cache
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-
      # - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      # install c++ dependencies and install necessary packages
      - run: R -e 'renv::restore()'
      # execute Rscript
      - run: Rscript email.R
